spring:
  main:
    banner-mode: off

  application:
    name: banking-app

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:mem:bankingDB
    driver-class-name: org.h2.Driver
    username: admin
    password: password

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
