spring:
  application:
    name: jwt-auth

  datasource:
    url: jdbc:h2:mem:JwtDB
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
