spring:
  application:
    name: basic-auth-security

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
    url: jdbc:h2:mem:basicAuthDB

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org:
      springframework:
        security: trace