spring:

# basic spring config
  application:
    name: virgin-security
  main:
    banner-mode: off

# database configuration
  datasource:
    username: sa
    password: password
    driver-class-name: org.h2.Driver

# jpa and hibernate orm configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# database specific config
  h2:
    console:
      enabled: true
      path: /h2-console

